[package]
name = "pre-man"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
httpstatus = "0.1.2"
reqwest = "0.12.24"
tokio = { version = "1.48.0", features = ["full"] }
